### ISSUE TITLE
Doubling author & title

### ISSUE THREAD

**Issue by oncomouse** [c-forster/om-guidelines#3]
In the TS Eliot example in the documentation, we double the instances of the author and the title:

``` markdown

---
title: '*Ulysses*, Order, and Myth'
author: 
    family: Eliot
    given: T. S.

citation:
    title: '*Ulysses*, Order, and Myth'
    author:
        family: Eliot
        given: T. S.

---
```

What's the reason for having title / author both inside and out of the citation object? Is there ever a moment where `citation` would contain an author / title different from the documents overall author / title?

I think the author / title could be removed from the citation definition and just allowed to exist in the main metadata block.

**Comment by c-forster** [comment]
I agree; I'm wary of a case where for some reason we would want to have both---say an article that was unattributed in its appearance, but which _we know_ was by Author X, or similar. I'm going to remove it for now--it would be relatively easy to default to using the main author, but then allowing a separate `citation` author if needed.
